import os
import argparse
import pandas as pd

def compare_panaroo_blast_v2(panaroo_file, blast_file, filterfile, output_file):
    # read in the panaroo presence/absence matrix
    pandf = read_panaroo_data(panaroo_file, filterfile)
    # read in the blast results
    blastdf = read_blast_data_v3(blast_file)
    # for each gene family, write out the number of isolates with each type of blast outcome
    with open(output_file, 'w') as out_f:
        header_line_done = False
        for gene_fam in blastdf:
            if gene_fam not in pandf['Gene'].values:
                print(f'{gene_fam} not found in panaroo data')
                quit(1)
            out_data = {}
            gene_fam_row_index = pandf[pandf['Gene'] == gene_fam].index[0]
            pan_data_series = pandf.loc[gene_fam_row_index]
            # remove the Gene column
            pan_data_series = pan_data_series.drop('Gene')
            # get the index names that have non-empty entries - note that panaroo_presence will include refound and pseudo genes
            panaroo_presence = set(pan_data_series[pan_data_series != ''].index)
            panaroo_absence = set(pan_data_series[pan_data_series == ''].index)
            out_data['p_pan'] = len(panaroo_presence)
            out_data['a_pan'] = len(panaroo_absence)
            for key in blastdf[gene_fam]:
                key_presence = len(panaroo_presence & blastdf[gene_fam][key])
                out_data[f'p_{key}'] = key_presence
                key_absence = len(panaroo_absence & blastdf[gene_fam][key])
                out_data[f'a_{key}'] = key_absence
            out_line = ''
            for key in out_data:
                out_line += f'\t{out_data[key]}'
            if not header_line_done:
                header_line = 'Gene_Family'
                for key in out_data:
                    header_line += f'\t{key}'
                out_f.write(f'{header_line}\n')
                header_line_done = True
            out_f.write(f'{gene_fam}{out_line}\n')


def read_blast_data_v3(blast_file):
    blastdict = {}
    with open(blast_file, 'r') as fhin:
        next(fhin)
        for line in fhin:
            query_seqid, subject_seqid, expected_neighbors, found_neighbors, good_blast_hit = line.strip().split('\t')
            if query_seqid not in blastdict:
                blastdict[query_seqid] = {'nohit': set(), '2e2n': set(), '2e1n': set(), '2e0n': set(), '1e1n': set(), '1e0n': set(), '0e0n': set()}
            key = ''
            if good_blast_hit == 'False':
                key = 'nohit'
            else:
                key = f'{expected_neighbors}e{found_neighbors}n'
            blastdict[query_seqid][key].add(subject_seqid)
    return blastdict


def read_panaroo_data(panaroo_file, filterfile):
    pan = pd.read_csv(panaroo_file,keep_default_na=False)
    # subset pan to only contain columns for the gene family names and isolates
    pan = pan.loc[:, pan.columns.str.startswith(("Gene", "SRR", "ARR", "DRR", "ERR", "UM_", "Chi_", "b8441"))]
    # subset pan to only include isolates in the filter file, if provided
    if filterfile is not None:
        with open(filterfile, 'r') as fh:
            filter_list = [line.strip() for line in fh]
        # always keep the 'Gene' column
        filter_list.append('Gene')
        # include only the columns in the filter list
        pan = pan.loc[:, pan.columns.isin(filter_list)]
    return pan

def check_boolean_arg(input_str):
    if input_str.lower() in ['true', 't', '1']:
        return True
    elif input_str.lower() in ['false', 'f', '0']:
        return False
    else:
        print('Error: Boolean required for --neighbor_mode')
        quit(1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--blast','-b',type=str,
        help='''Provide a BLAST summary file generated by the read_blast script.''',
        required=True
        )
    parser.add_argument(
        '--panaroo','-p',type=str,
        help='''Provide Panaroo presence/absence matrix file in the csv format. This should be the same file the gene families in the 
        input list are drawn from, and the same file used with extract_gene_from_isolate. Gene names should be present in this file.''',
        required=True
        )
    parser.add_argument(
        '--filterfile','-ff',type=str,
        help='''Provide a path to a one-column csv consisting only of isolate names. Only isolates in this file will be used.''',
        default=None
        )
    parser.add_argument(
        '--output','-o',type=str,
        help='''Provide a file name for the output file.''',
        required=True
        )
    # add a flag for neighbor mode
    parser.add_argument(
        '--neighbor_mode',type=str,
        help='''Add this flag if you included neighbor analysis on the read_blast step.''',
        required=False,default='False'
        )
    parser.add_argument(
        '--confidence','-c',choices=['high_confidence','medium_confidence','low_confidence','all'],type=str,
        help='''Provide a minimum confidence level for the comparison.''',
        required=True, default='all'
        )
    args = parser.parse_args()
    args.neighbor_mode = check_boolean_arg(args.neighbor_mode)
    compare_panaroo_blast_v2(args.panaroo, args.blast, args.filterfile, args.output)


if __name__ == '__main__':
    main()